ktor:
  deployment:

    sslPort: 8444
  application:
    modules:
      - com.example.ApplicationKt.module
  security:
    ssl:
      keyStore: keystore.p12
      keyAlias: tasknote
      keyStorePassword: "971358"
      privateKeyPassword: "971358"

database:
  url: "jdbc:postgresql://localhost:5432/tasknote_db"
  driver: "org.postgresql.Driver"
  user: "khobaituddinsimran"
  password: "YourNewSecurePassword123"