ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.example.ApplicationKt.module

database:
  url: "jdbc:postgresql://localhost:5432/tasknote_db"
  driver: "org.postgresql.Driver"
  user: "khobaituddinsimran"
  password: "YourNewSecurePassword123"